import Head from "next/head";

import { Container } from "react-bulma-components";
import HeroSection from "../components/HeroSection";
import { fetchAPI } from "../lib/api";

import Layout from "../components/_App/Layout";
import AboutMe from "../components/AboutMe";

import { GetStaticProps } from "next/types";
import { LandingData } from "../types/types";

interface Props {
  landing: LandingData;
}

const HomePage = ({ landing }: Props): JSX.Element => {
  return (
    <Layout>
      <Head>
        <title>Mauro S. - Full Stack Web Developer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <HeroSection data={landing} />

        <AboutMe data={landing.attributes.about} />
      </Container>
    </Layout>
  );
};

export default HomePage;

export const getStaticProps: GetStaticProps = async () => {
  const landingRes = await fetchAPI("/landing", { populate: "*" });

  return {
    props: {
      landing: landingRes?.data,
    },
    revalidate: 1,
  };
};
