import Head from 'next/head'
import Image from 'next/image'
import HeroSection from '../components/HeroSection'
import { fetchAPI } from '../lib/api'

export async function getStaticProps() {

  const landingRes = await fetchAPI("/landing", { populate: "*" });


  return {
    props: {
      landing: landingRes?.data,

    },
    revalidate: 1,
  }

}


export default function Home({ landing }) {


  return (
    <div>
      <Head>
        <title>Mauro S. - Full Stack Web Developer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection data={landing} />


    </div >
  )
}


